export const DEFAULT_LOCALE = "en";
export const LOCALES = [
  { id: "en", label: "EN", name: "English" },
  { id: "ru", label: "RU", name: "Русский" },
  { id: "fr", label: "FR", name: "Français" },
  { id: "it", label: "IT", name: "Italiano" },
  { id: "zh", label: "中文", name: "中文" }
];

const commonTypes = {
  en: ["Hero", "Navigation", "Dashboard", "Application shell", "Data table", "Logos", "Features", "Content", "Steps", "Call to action", "Pricing", "Testimonials", "FAQ", "Footer", "Other"],
  ru: ["Первый экран", "Навигация", "Дашборд", "Каркас приложения", "Таблица данных", "Логотипы", "Преимущества", "Контент", "Этапы", "Призыв к действию", "Тарифы", "Отзывы", "Частые вопросы", "Подвал", "Другое"],
  fr: ["Bannière principale", "Navigation", "Tableau de bord", "Structure d’application", "Tableau de données", "Logos", "Fonctionnalités", "Contenu", "Étapes", "Appel à l’action", "Tarifs", "Témoignages", "FAQ", "Pied de page", "Autre"],
  it: ["Sezione principale", "Navigazione", "Dashboard", "Struttura applicazione", "Tabella dati", "Loghi", "Funzionalità", "Contenuto", "Passaggi", "Invito all’azione", "Prezzi", "Testimonianze", "FAQ", "Piè di pagina", "Altro"],
  zh: ["首屏", "导航", "仪表盘", "应用框架", "数据表", "徽标", "功能", "内容", "步骤", "行动号召", "定价", "用户评价", "常见问题", "页脚", "其他"]
};

const typeKeys = ["hero", "navigation", "dashboard", "applicationShell", "dataTable", "logos", "features", "content", "steps", "cta", "pricing", "testimonials", "faq", "footer", "other"];

const base = {
  en: { designIntent:"DESIGN INTENT",projectSettings:"Project settings",project:"Project",page:"Page",targetRoute:"Target route",newBlock:"NEW BLOCK",sectionType:"Section type",position:"Position",implementationNotes:"Implementation notes",notesPlaceholder:"What should the agent preserve, replace, or remove?",discard:"Discard",addBlock:"Add block",currentPage:"CURRENT PAGE",emptyHint:"Open a Shadcn Block and capture it.",copyPrompt:"Copy prompt",finishPage:"Finish page",moveUp:"Move up",moveDown:"Move down",removeBlock:"Remove block",blockDiscarded:"Block discarded",discardFailed:"Could not discard block",blockAdded:"Block added",promptCopied:"Prompt copied",saved:"Saved",exportFailed:"Export failed",captureFailed:"Could not capture the block",unknownError:"unknown error",specTitle:"Page Build Specification",source:"Source",install:"Install",changes:"Changes",fallbackChange:"Adapt the source content to the target project.",generalInstructions:"General instructions",generalText:"Follow the existing project's design tokens, typography, colors, containers, responsive conventions, and component architecture. Do not blindly copy demo content. Reuse existing components and assets.",agentInstructions:"Agent implementation instructions",agentSteps:["Inspect the repository before modifying code.","Install selected blocks through the configured registry.","Adapt blocks to the existing design system.","Do not introduce duplicate primitives.","Preserve responsive behavior and accessibility.","Run lint, typecheck, and tests.","Update relevant documentation."],sourceLibrary:"Source library",framework:"Framework"},
  ru: { designIntent:"ЗАМЫСЕЛ СТРАНИЦЫ",projectSettings:"Настройки проекта",project:"Проект",page:"Страница",targetRoute:"Целевой маршрут",newBlock:"НОВЫЙ БЛОК",sectionType:"Тип секции",position:"Позиция",implementationNotes:"Инструкции по реализации",notesPlaceholder:"Что агент должен сохранить, заменить или удалить?",discard:"Отказаться",addBlock:"Добавить блок",currentPage:"ТЕКУЩАЯ СТРАНИЦА",emptyHint:"Откройте блок Shadcn и добавьте его.",copyPrompt:"Копировать задание",finishPage:"Завершить страницу",moveUp:"Переместить выше",moveDown:"Переместить ниже",removeBlock:"Удалить блок",blockDiscarded:"Блок отклонён",discardFailed:"Не удалось отклонить блок",blockAdded:"Блок добавлен",promptCopied:"Задание скопировано",saved:"Сохранено",exportFailed:"Ошибка экспорта",captureFailed:"Не удалось получить блок",unknownError:"неизвестная ошибка",specTitle:"Спецификация сборки страницы",source:"Источник",install:"Установка",changes:"Изменения",fallbackChange:"Адаптировать содержимое блока под целевой проект.",generalInstructions:"Общие инструкции",generalText:"Следовать дизайн-токенам, типографике, цветам, контейнерам, адаптивным правилам и архитектуре существующего проекта. Не копировать демонстрационный контент без адаптации. Переиспользовать существующие компоненты и ресурсы.",agentInstructions:"Инструкции агенту",agentSteps:["Изучить репозиторий до внесения изменений.","Установить выбранные блоки через настроенный registry.","Адаптировать блоки к существующей дизайн-системе.","Не создавать дублирующиеся примитивы.","Сохранить адаптивность и доступность.","Запустить lint, typecheck и тесты.","Обновить документацию."],sourceLibrary:"Источник блоков",framework:"Фреймворк"},
  fr: { designIntent:"INTENTION DE DESIGN",projectSettings:"Paramètres du projet",project:"Projet",page:"Page",targetRoute:"Route cible",newBlock:"NOUVEAU BLOC",sectionType:"Type de section",position:"Position",implementationNotes:"Instructions d’implémentation",notesPlaceholder:"Que doit conserver, remplacer ou supprimer l’agent ?",discard:"Ignorer",addBlock:"Ajouter le bloc",currentPage:"PAGE ACTUELLE",emptyHint:"Ouvrez un bloc Shadcn et ajoutez-le.",copyPrompt:"Copier le prompt",finishPage:"Terminer la page",moveUp:"Déplacer vers le haut",moveDown:"Déplacer vers le bas",removeBlock:"Supprimer le bloc",blockDiscarded:"Bloc ignoré",discardFailed:"Impossible d’ignorer le bloc",blockAdded:"Bloc ajouté",promptCopied:"Prompt copié",saved:"Enregistré",exportFailed:"Échec de l’export",captureFailed:"Impossible de capturer le bloc",unknownError:"erreur inconnue",specTitle:"Spécification de construction de page",source:"Source",install:"Installation",changes:"Modifications",fallbackChange:"Adapter le contenu source au projet cible.",generalInstructions:"Instructions générales",generalText:"Respecter les tokens de design, la typographie, les couleurs, les conteneurs, les conventions responsives et l’architecture du projet existant. Ne pas copier aveuglément le contenu de démonstration. Réutiliser les composants et ressources existants.",agentInstructions:"Instructions d’implémentation pour l’agent",agentSteps:["Inspecter le dépôt avant toute modification.","Installer les blocs sélectionnés via le registre configuré.","Adapter les blocs au système de design existant.","Ne pas créer de primitives en double.","Préserver le responsive et l’accessibilité.","Exécuter lint, typecheck et les tests.","Mettre à jour la documentation pertinente."],sourceLibrary:"Bibliothèque source",framework:"Framework"},
  it: { designIntent:"INTENTO DI DESIGN",projectSettings:"Impostazioni progetto",project:"Progetto",page:"Pagina",targetRoute:"Route di destinazione",newBlock:"NUOVO BLOCCO",sectionType:"Tipo di sezione",position:"Posizione",implementationNotes:"Istruzioni di implementazione",notesPlaceholder:"Cosa deve mantenere, sostituire o rimuovere l’agente?",discard:"Scarta",addBlock:"Aggiungi blocco",currentPage:"PAGINA CORRENTE",emptyHint:"Apri un blocco Shadcn e acquisiscilo.",copyPrompt:"Copia prompt",finishPage:"Completa pagina",moveUp:"Sposta in alto",moveDown:"Sposta in basso",removeBlock:"Rimuovi blocco",blockDiscarded:"Blocco scartato",discardFailed:"Impossibile scartare il blocco",blockAdded:"Blocco aggiunto",promptCopied:"Prompt copiato",saved:"Salvato",exportFailed:"Esportazione non riuscita",captureFailed:"Impossibile acquisire il blocco",unknownError:"errore sconosciuto",specTitle:"Specifica di costruzione della pagina",source:"Fonte",install:"Installazione",changes:"Modifiche",fallbackChange:"Adattare il contenuto sorgente al progetto di destinazione.",generalInstructions:"Istruzioni generali",generalText:"Seguire i design token, la tipografia, i colori, i contenitori, le convenzioni responsive e l’architettura del progetto esistente. Non copiare alla cieca il contenuto demo. Riutilizzare componenti e risorse esistenti.",agentInstructions:"Istruzioni di implementazione per l’agente",agentSteps:["Esaminare il repository prima di apportare modifiche.","Installare i blocchi selezionati tramite il registry configurato.","Adattare i blocchi al design system esistente.","Non introdurre primitive duplicate.","Mantenere responsive design e accessibilità.","Eseguire lint, typecheck e test.","Aggiornare la documentazione pertinente."],sourceLibrary:"Libreria sorgente",framework:"Framework"},
  zh: { designIntent:"页面设计意图",projectSettings:"项目设置",project:"项目",page:"页面",targetRoute:"目标路由",newBlock:"新模块",sectionType:"模块类型",position:"位置",implementationNotes:"实现说明",notesPlaceholder:"智能体应保留、替换或删除哪些内容？",discard:"放弃",addBlock:"添加模块",currentPage:"当前页面",emptyHint:"打开一个 Shadcn 模块并采集它。",copyPrompt:"复制提示词",finishPage:"完成页面",moveUp:"上移",moveDown:"下移",removeBlock:"删除模块",blockDiscarded:"已放弃模块",discardFailed:"无法放弃模块",blockAdded:"模块已添加",promptCopied:"提示词已复制",saved:"已保存",exportFailed:"导出失败",captureFailed:"无法采集模块",unknownError:"未知错误",specTitle:"页面构建规范",source:"来源",install:"安装",changes:"修改要求",fallbackChange:"根据目标项目调整源内容。",generalInstructions:"通用说明",generalText:"遵循现有项目的设计令牌、排版、颜色、容器、响应式规范和组件架构。不要直接照搬演示内容。尽可能复用现有组件和资源。",agentInstructions:"智能体实现说明",agentSteps:["修改代码前先检查仓库。","通过已配置的 registry 安装所选模块。","让模块适配现有设计系统。","不要引入重复的基础组件。","保持响应式行为和可访问性。","运行 lint、typecheck 和测试。","更新相关文档。"],sourceLibrary:"模块来源",framework:"框架"}
};

export const MESSAGES = Object.fromEntries(Object.entries(base).map(([locale, messages]) => [locale, { ...messages, types: Object.fromEntries(typeKeys.map((key, index) => [key, commonTypes[locale][index]])) }]));
export function translate(locale, key) { return MESSAGES[locale]?.[key] ?? MESSAGES[DEFAULT_LOCALE][key] ?? key; }
